var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                           o                    ",
   "                                                                                ",
   "                                                                                ",
   "                                                   xx      xx                   ",
   "                                    o        xx     d       d                   ",
   "                                             d                                  ",
   "                                   xxxxx                                        ",
   "                                    ddd                                         ",
   "  xx                                        xxx         o                       ",
   "  x                     o                    d                                  ",
   "  x                   xxxx                        xxxxx                    o    ",
   "  x                   xddx                         ddd                          ",
   "  x  @                xddx                xxxx                  xxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxx   xxxxxxddxxxxxxxxxxxxxx   dd                    dddddddddddddddd",
   "  dddddddddddd!!!dddddddddddddddddddddd!!!!!!!!!!!!!!!!!!!!!!!!!d               ",
   "             d!!!d                    d!!!!!!!!!!!!!!!!!!!!!!!!!d               ",
   "             ddddd                    d!!!!!!!!!!!!!!!!!!!!!!!!!d               ",
   "                                      ddddddddddddddddddddddddddd               ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                           o                                      ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                    xxx                           ",
   "                                                                                    d d                           ",
   "                                 =                                                                                ",
   "                                                                           xxxx                                   ",
   "                                                                             d                                    ",
   "                                                                                                                  ",
   "                    o                                                                                             ",
   "                                                                 xxxxxx            o       xxxxxx                 ",
   "                                                                    dd                        ddd                 ",
   "                                              =                                                                   ",
   "               xxx                                                                                     xx         ",
   "               ddd                        o                                 xxxxx                       d         ",
   "          xx   dd                                                            dd                                   ",
   "    @      d   d   =                        xxx                                                                   ",
   "    xxx        d    xx   xx     xx          ddd                   xxxxx                                           ",
   "!!!!ddd!!!!!!!!d     d    d     d     xx    ddd        xxxx       d  dd                                           ",
   "!!!!ddd!!!!!!!!d                       d    dd          dd                                                     o  ",
   "dddddddddddddddddd                          dd                                                                xxxx",
   "                 d!!!!!!!!!!!!!!!!!!!!!!!!!!d!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!ddd"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                          v                                   ",
   "                                                                                                       v      ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                         v                    ",
   "                        v                                                                                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                              v                          o                    ",
   "                                                                                                              ",
   "                                   v                                                                          ",
   "                                                                                                              ",
   "                  v          o                                                      xxx      xx               ",
   "                                                                                     d        d               ",
   "                                                                                                              ",
   "                                                                     =                                        ",
   "                            xxx               o                               xxx                 xx          ",
   "                             d                xxx                              d                   d          ",
   "         =                                     d                                                              ",
   "                    xxx      o         xxx          xxx                            xxx                     o  ",
   "  xxx                d                  d            d                              d                    xxxdd",
   "  x x                                                                                                    x d  ",
   "  x                         xxx                                              xxx                           d  ",
   "  x                          d                                                d                            d  ",
   "  x                                       =                                                                d  ",
   "  x                 xxx                                 xxx            xxx                                 d  ",
   "  x                  d                                   d              d                                  d  ",
   "  x                                                                                                        d  ",
   "  x            xxx                                                xxx                                      d  ",
   "  x     @       d                                                  d                                       d  ",
   "  x  dddddd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!d  ",
   "  dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                         o                                    ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                          dd                                                                                  ",
   "                          d                                              x                                    ",
   "                          d                                                                                   ",
   "                          d                                                                                   ",
   "                          d                                                                                   ",
   "                    xx    d                                         x                                         ",
   "                     d    d                                                                                   ",
   "                          d                                                                                   ",
   "                xx        d                                    xx                                             ",
   "                 d        d                                    d                    o                         ",
   "          o               d                      o                                                            ",
   "    x     xx              d                               xx                                                  ",
   "    d      d             dd                                d                                                  ",
   "    d      d                                                                                                  ",
   "    d     dd          o                      xxxxxxxxxx                                                       ",
   "    d     d          xxx                      d      dd                                                       ",
   "    dd    d          d              xxx                                                                       ",
   "    dd    d                           d                                                                       ",
   "    d     d                                                                                                   ",
   "    d    dd                 xxx                                                                               ",
   "    d     d                  d                                                                                ",
   "     d    d                                                                                                   ",
   "    dd    d                                                                                                   ",
   "    d    dd                                                                                                   ",
   "    d@   d                                                                                                    ",
   "    dd   d                                                                                                    ",
   "     d   d!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ",
   "dddddd!!!ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
